name: CachyOS Builder CI

run-name: >
  ${{ github.event_name == 'schedule' && '🕒 Scheduled CachyOS Build' || 
      github.event.inputs.target_cpu && format('🎯 Targeted Retry ({0}) for CachyOS', github.event.inputs.target_cpu) || 
      '🏗️ Standard CachyOS Build' }}

on:
  push:
    branches: [ main ]
    paths: [ 'cachy/Dockerfile' ]
  workflow_dispatch:
    inputs:
      target_cpu:
        description: 'Hunt for specific CPU'
        required: false
        type: choice
        options: ['', 'v3', 'v4']
  schedule:
    # Runs Everyday at 03:00 UTC
    - cron: '0 3 * * *'

concurrency:
  group: cachy-base-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'push' }}

jobs:
  launch-pipeline:
    uses: ./.github/workflows/reusable-builder.yml
    with:
      target_cpu: ${{ inputs.target_cpu }}
      docker_id: "cachy-base"
      build_context: "cachy"
      title_suffix: "Balanced Runtime"
      desc_suffix: "Runtime with Essential CLI and Build Utilities"
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

